name = "Lilium"
license = "MIT"
licenselink = "https://raw.githubusercontent.com/igaozp/hugo-theme-lilium/main/LICENSE"
description = ""
homepage = "https://hugo-theme-lilium.vercel.app/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "igaozp"
  homepage = "https://andornot.xyz"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
